stages:

  #stage 1- data ingestion
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - src/connections/s3_connection.py
      - params.yaml
    params:
      - data_ingestion
    outs:
      - dvc_data/raw/transactions_raw.parquet
      - dvc_data/raw/accounts_raw.parquet

  #stage 2 - data preprocessing
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - dvc_data/raw/transactions_raw.parquet
      - dvc_data/raw/accounts_raw.parquet
      - params.yaml
    params:
      - data_preprocessing
    outs:
      - dvc_data/processed/transactions_processed.parquet
      - dvc_data/processed/accounts_processed.parquet

  #stage 3 - feature engineering
  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
      - src/features/feature_engineering.py
      - src/features/build_features.py
      - src/features/experimental/base_features.py
      - src/features/experimental/rolling_features_v2.py
      - src/features/experimental/advanced_rolling_features_v2.py
      - src/features/experimental/counterparty_entropy_features_v2.py
      - src/features/experimental/network_features.py
      - src/features/experimental/toxic_corridors.py
      - src/features/experimental/ratio_features.py
      - src/features/experimental/derived_features.py
      - src/features/experimental/precompute_entity_stats.py
      - dvc_data/processed/transactions_processed.parquet
      - dvc_data/processed/accounts_processed.parquet
      - params.yaml
    params:
      - feature_engineering
    outs:
      - dvc_data/aml_features/train_features.parquet
      - dvc_data/aml_features/val_features.parquet
      - dvc_data/aml_features/test_features.parquet

  #stage 3.5 - anomaly scoring
  anomaly_scoring:
    cmd: python src/features/anomaly_feature_scoring.py
    deps:
      - src/features/anomaly_feature_scoring.py
      - dvc_data/aml_features/train_features.parquet
      - dvc_data/aml_features/val_features.parquet
      - dvc_data/aml_features/test_features.parquet
      - params.yaml
    params:
      - anomaly
    outs:
      - dvc_data/processed_with_anomaly/train_features.parquet
      - dvc_data/processed_with_anomaly/val_features.parquet
      - dvc_data/processed_with_anomaly/test_features.parquet
      - models/anomaly/isolation_forest.pkl:
          cache: true

  #stage 4 - model buildling
  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - dvc_data/processed_with_anomaly/train_features.parquet
      - dvc_data/processed_with_anomaly/val_features.parquet
      - dvc_data/processed_with_anomaly/test_features.parquet
      - params.yaml
    params:
      - model
    outs:
      - models/trained_model/:
          cache: true
    metrics:
      - reports/model_metrics.json:
          cache: false

  #stage 5 - model evaluation
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - dvc_data/processed_with_anomaly/test_features.parquet
      - params.yaml
    params:
      - model
      - dagshub
      - mlflow
    outs:
      - reports/experiment_info.json:
          cache: false
      - reports/confusion_matrix.png:
          cache: false
      - reports/pr_curve.png:
          cache: false
    metrics:
      - reports/eval_metrics.json:
          cache: false

  #stage 6 - model registry
  model_registry:
    cmd: python src/model/model_registry.py
    deps:
      - src/model/model_registry.py
      - reports/experiment_info.json
      - reports/metrics.json
      - params.yaml
    params:
      - model_registry
      - dagshub
    outs:
      - reports/registry_output.json:
          cache: false